### ISSUE TITLE
Add retrieval of skipped/ignored tests

### ISSUE THREAD

**Issue by heiglandreas** [heiglandreas/JUnitDiff#3]
Currently skipped and ignored tests are not checked. That should changed ;)

**Comment by sebastianbergmann** [comment]
You wrote "Currently the JUnit-log file does not provide information (Or I was too stubborn to find it) about skipped or ignored tests." in your `README.md`.

PHPUnit 4.8 and PHPUnit 5.7 do not include incomplete and skipped tests in the JUnit XML logfile due to backward compatibility reasons.

PHPUnit 6.0 includes incomplete and skipped tests in the JUnit XML logfile. See https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed.

**Comment by heiglandreas** [comment]
Awesome! Thanks for the update! I'll change that in the README

**Comment by heiglandreas** [comment]
Skipped and Ignored tests can be retrieved since merging #26
